name: build_network_setting
sdkPath: .fvm/flutter_sdk

packages:
  - packages/app/*
  - packages/api/**
  - packages/mock_setting/*

scripts:
  format: 
    run: fvm flutter format --fix packages
  
  build_runner:
    exec: fvm flutter packages pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: 'build_runner'

  api:
    run: |
      yarn gen:api
      melos format
    description: generate api from OpenApi

  run:mock:
    exec: fvm flutter run --target lib/main-mock.dart
    select-package:
      scope: 'app'

  run:release:
    exec: fvm flutter run --target lib/main.dart
    select-package:
      scope: 'app'


  test:unit:
    exec: fvm flutter test
    select-package:
      dir-exists:
        - test
