name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  external_todo:
    path: ../api/external/todo

  cupertino_icons: ^1.0.2
  riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  state_notifier: ^0.7.2+1
  flutter_flavor: ^3.1.1
  go_router: ^5.2.4
  bot_toast: ^4.0.3
  logger: ^1.1.0

dev_dependencies:
  build_runner:
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  freezed: ^2.3.2

  mock_setting:
    path: ../mock_setting

flutter:

  uses-material-design: true
