name: mock_setting
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  source_gen: ^1.2.6
  code_builder: ^4.3.0
  dart_style: ^2.2.4

dev_dependencies:
  lints: ^1.0.0